#!/usr/bin/env bash
# Repo index generator (package section 3.4).
#
# Writes docs/index/: one markdown file per module + _overview.md with the
# module table, dependency edges, and entry points. Generated only — the whole
# directory is owned by this script; never hand-edit it.
#
#   scripts/build-index.sh          rebuild the index
#   scripts/build-index.sh --check  exit 1 (with a message) if the index is
#                                   stale relative to HEAD; used by
#                                   /refresh-index and /validate-phase
#
# Format rationale: markdown-per-module, not one JSON blob, because the index
# is read by sessions (one section at a time, P1), reviewed by humans, and
# diffed in git. Traded away: machine-precise symbol data. Symbols come from
# universal-ctags when installed, else a grep heuristic over declaration
# keywords — good enough to locate files, which is the whole job.
set -euo pipefail

ROOT="${CLAUDE_PROJECT_DIR:-$PWD}"
cd "$ROOT"
OUTDIR="docs/index"
STAMP_RE='<!-- workflow-index-stamp: ([0-9a-f]+|no-commits) -->'

git rev-parse --git-dir >/dev/null 2>&1 || { echo "build-index: not a git repository" >&2; exit 1; }
HEAD="$(git rev-parse --short HEAD 2>/dev/null || echo no-commits)"

SRC_EXT='py|js|jsx|ts|tsx|mjs|cjs|go|rs|rb|java|kt|kts|c|h|cc|cpp|hpp|cs|php|swift|scala|ex|exs|lua|sh'

# --- staleness check mode ---------------------------------------------------
if [ "${1:-}" = "--check" ]; then
  OV="$OUTDIR/_overview.md"
  [ -f "$OV" ] || { echo "index STALE: $OV missing — run scripts/build-index.sh"; exit 1; }
  stamp="$(grep -oE "$STAMP_RE" "$OV" | grep -oE '[0-9a-f]+|no-commits' | tail -1 || true)"
  [ -n "$stamp" ] || { echo "index STALE: no stamp in $OV — run scripts/build-index.sh"; exit 1; }
  [ "$stamp" = "$HEAD" ] && { echo "index fresh ($HEAD)"; exit 0; }
  if git diff --name-only "$stamp" HEAD 2>/dev/null | grep -qE "\.($SRC_EXT)\$"; then
    echo "index STALE: built at $stamp, HEAD is $HEAD and source files changed — run scripts/build-index.sh"
    exit 1
  fi
  echo "index fresh enough ($stamp -> $HEAD touched no source files)"
  exit 0
fi

# --- collect source files (tracked + untracked-but-not-ignored) -------------
FILES="$(git ls-files -co --exclude-standard | grep -E "\.($SRC_EXT)\$" | grep -vE '^(docs|\.claude)/' || true)"
if [ -z "$FILES" ]; then
  echo "build-index: no source files found — nothing to index"
  exit 0
fi

mkdir -p "$OUTDIR"
rm -f "$OUTDIR"/*.md   # directory is fully generated; stale module files must not linger

# module key per file: <root>/<child> under container dirs (src, lib, ...), else <root>
map_module() {
  awk -F/ '{
    if (NF == 1) { print "(root)\t" $0 }
    else if (NF >= 3 && ($1=="src" || $1=="lib" || $1=="app" || $1=="apps" || $1=="packages" || $1=="internal" || $1=="cmd" || $1=="pkg")) { print $1"/"$2 "\t" $0 }
    else { print $1 "\t" $0 }
  }'
}
MAPPED="$(printf '%s\n' "$FILES" | map_module)"
MODULES="$(printf '%s\n' "$MAPPED" | cut -f1 | sort -u)"

HAVE_CTAGS=0
command -v ctags >/dev/null 2>&1 && ctags --version 2>/dev/null | grep -qi universal && HAVE_CTAGS=1

symbols_of() { # symbols_of <file> — markdown bullet list of public-ish symbols
  local f="$1"
  if [ "$HAVE_CTAGS" = 1 ]; then
    { ctags -x --sort=no "$f" 2>/dev/null | awk '{printf "- %s `%s` (L%s)\n", $2, $1, $3}' | head -40; } || true
  else
    { grep -nE '^[[:space:]]*(export[[:space:]]|export default|module\.exports|exports\.[a-zA-Z]|pub[[:space:]]|public[[:space:]]|def[[:space:]]|async def[[:space:]]|class[[:space:]]|function[[:space:]]|func[[:space:]]|fn[[:space:]]|interface[[:space:]]|struct[[:space:]]|trait[[:space:]]|module[[:space:]]|type[[:space:]][A-Z])' "$f" 2>/dev/null \
      | head -40 \
      | sed -E 's/^([0-9]+):[[:space:]]*(.{0,100}).*$/- L\1: `\2`/'; } || true
  fi
}

IMPORT_RE='^[[:space:]]*(import|from|require|include|use|using|#include)[[:space:](]|require\(|import\('

# imports_of <module> — all import-ish lines in the module, deduped
imports_of() {
  local m="$1" f
  while IFS=$'\t' read -r mod f; do
    [ "$mod" = "$m" ] || continue
    grep -hE "$IMPORT_RE" "$f" 2>/dev/null || true
  done <<<"$MAPPED" | sort -u
}

# --- per-module pages + edge collection -------------------------------------
EDGES=""
for m in $MODULES; do
  slug="$(printf '%s' "$m" | tr '/()' '-' | sed 's/^-*//;s/-*$//')"
  [ -n "$slug" ] || slug="root"
  page="$OUTDIR/$slug.md"

  mfiles="$(printf '%s\n' "$MAPPED" | awk -F'\t' -v m="$m" '$1==m {print $2}')"
  nfiles="$(printf '%s\n' "$mfiles" | wc -l | tr -d ' ')"
  nlines="$(printf '%s\n' "$mfiles" | xargs wc -l 2>/dev/null | tail -1 | awk '{print $1}')"

  {
    echo "# Module: $m"
    echo "<!-- generated by scripts/build-index.sh — do not edit; regenerate with /refresh-index -->"
    echo ""
    echo "Files: $nfiles · Lines: ${nlines:-?}"
    echo ""
    echo "## Files and public symbols"
    while read -r f; do
      [ -n "$f" ] || continue
      echo ""
      echo "### $f ($(wc -l <"$f" | tr -d ' ') lines)"
      syms="$(symbols_of "$f")"
      [ -n "$syms" ] && echo "$syms" || echo "_no declarations detected_"
    done <<<"$mfiles"
  } >"$page"

  # ponytail: O(modules²) substring scan for edges; fine below ~100 modules,
  # switch to a real import resolver if it ever isn't.
  mimports="$(imports_of "$m")"
  deps=""
  for other in $MODULES; do
    [ "$other" = "$m" ] && continue
    [ "$other" = "(root)" ] && continue
    obase="$(basename "$other")"
    if printf '%s\n' "$mimports" | grep -qE "$other|[/\"'[:space:].]$obase[/\"']"; then
      deps="$deps $other"
      EDGES="$EDGES$m -> $other
"
    fi
  done
  {
    echo ""
    echo "## Depends on"
    if [ -n "$deps" ]; then for d in $deps; do echo "- $d"; done; else echo "_none detected_"; fi
  } >>"$page"
done

# --- overview ---------------------------------------------------------------
ENTRY_POINTS="$(printf '%s\n' "$FILES" | grep -E '(^|/)(main|index|app|server|cli|__main__|entry)\.[a-z]+$|(^|/)cmd/[^/]+/main\.go$' || true)"

{
  echo "# Repo index"
  echo "<!-- generated by scripts/build-index.sh — do not edit -->"
  echo "<!-- workflow-index-stamp: $HEAD -->"
  echo ""
  echo "Built: $(date -u +%Y-%m-%dT%H:%M:%SZ) at commit \`$HEAD\`."
  echo "Load only the module section you need — one file per module below."
  echo ""
  echo "## Modules"
  echo ""
  echo "| Module | Files | Index page |"
  echo "|--------|-------|------------|"
  for m in $MODULES; do
    slug="$(printf '%s' "$m" | tr '/()' '-' | sed 's/^-*//;s/-*$//')"
    [ -n "$slug" ] || slug="root"
    n="$(printf '%s\n' "$MAPPED" | awk -F'\t' -v m="$m" '$1==m' | wc -l | tr -d ' ')"
    echo "| $m | $n | [$slug.md]($slug.md) |"
  done
  echo ""
  echo "## Dependency edges (heuristic, import-based)"
  echo ""
  if [ -n "$EDGES" ]; then
    printf '%s' "$EDGES" | sort -u | sed 's/^/- /'
  else
    echo "_none detected_"
  fi
  echo ""
  echo "## Entry points"
  echo ""
  if [ -n "$ENTRY_POINTS" ]; then
    printf '%s\n' "$ENTRY_POINTS" | sed 's/^/- /'
  else
    echo "_none matched the entry-point name heuristic_"
  fi
} >"$OUTDIR/_overview.md"

echo "index written: $OUTDIR ($(printf '%s\n' "$MODULES" | wc -l | tr -d ' ') modules, stamp $HEAD)"
